version: 4.0.{build}.21

configuration: Release

platform: Any CPU

assembly_info:
  patch: true
  file: CVQMonitor\AssemblyInfo.fs
  assembly_version: '4.0.0.21'
  assembly_file_version: '{version}'
  assembly_informational_version: '4.0.21beta'

before_build:
- nuget restore

build:
  project: CVQMonitor.sln
  parallel: true
  verbosity: minimal

after_build:
- ps: .\NuGet\pack.ps1

artifacts:
- path: CVQMonitor\bin\Release\CVQMonitor.dll
  name: CVQMonitor.dll
- path: CVQMonitor\bin\Release\CVQMonitor.xml
  name: CVQMonitor.xml
- path: '**\CVQMonitor*.nupkg'

deploy:
- provider: NuGet
  api_key:
    secure: vVmfmmg09BJVlqMuiWrSGPo0LXGlJ8HzWfysbHPpZonMQMOd82oiB+1ioKZQEsZH
  skip_symbols: true
  artifact: /.*\.nupkg/
  on:
    branch: master
