version: 2.0.{build}.6

configuration: Release

platform: Any CPU

assembly_info:
  patch: true
  file: SOCVR.Net\Properties\AssemblyInfo.cs
  assembly_version: '2.0.0.6'
  assembly_file_version: '{version}'
  assembly_informational_version: '2.0.6-beta'

before_build:
- nuget restore

build:
  project: SOCVR.Net.sln
  parallel: true
  verbosity: minimal

after_build:
- ps: .\NuGet\pack.ps1

artifacts:
- path: SOCVR.Net\bin\Release\SOCVR.Net.dll
  name: SOCVR.Net.dll
- path: '**\SOCVR.Net*.nupkg'
  
deploy:
- provider: NuGet
  api_key:
    secure: vVmfmmg09BJVlqMuiWrSGPo0LXGlJ8HzWfysbHPpZonMQMOd82oiB+1ioKZQEsZH
  skip_symbols: true
  artifact: /.*\.nupkg/
  on:
    branch: master
